name: flutter_template
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_baidu_mapapi_base: ^3.7.1
  flutter_baidu_mapapi_map: ^3.7.1
  flutter_baidu_mapapi_utils: ^3.7.1
  flutter_baidu_mapapi_search: ^3.7.1
  flutter_bmflocation: ^3.6.0

  flutter_scankit: ^2.0.3
  flutter_easy_permission: ^1.1.2

  flutter_markdown: ^0.7.1
  flutter_screenutil: ^5.9.0
  go_router: ^13.2.4
  json_annotation: ^4.8.1
  location: ^6.0.1
  markdown: ^7.2.2
  shared_preferences: ^2.3.0
  table_calendar: ^3.1.2
  jiffy: ^6.3.1
  image_picker: ^1.1.2
  el_tooltip: ^2.0.0
  dio: ^5.5.0
  flutter_easyloading: ^3.0.5
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  audioplayers: ^6.0.0
  screenshot: ^3.0.0
  wechat_kit: ^6.0.1
  wechat_kit_extension: ^1.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  json_serializable: ^6.7.1
  go_router_builder: any
  build_runner: any
  build_verify: any

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/

wechat_kit:
  app_id: wx8d93f377eecbe1a9
